### ISSUE TITLE
where can find and download this linux system ?

### ISSUE THREAD

**Issue by cudnn** [antmicro/jetson-nano-baseboard#1]
where can find and download this linux system ?

**Comment by pkatarzynski** [comment]
Most of the IO interfaces available on board are supported by the default BSP provided by Nvidia
See https://developer.nvidia.com/embedded/downloads for more details.

**Comment by alexis-gruet-deel** [comment]
@pkatarzynski  : Just brought one unit via capable robot for testing. When you said "Most of the IO.." can you elaborate a bit more on that ? What are the IOs not supported by the BSP if any ?

**Comment by pkatarzynski** [comment]
You  will most likely need to adjust the BSP for camera (CSI) interfaces. The Ethernet, USB-C, HDMI, Displayport, M.2 (NVMe) are handled by the default JetPack provided by NVIDIA for the Jetson Nano or the Jetson Xavier NX

**Comment by alexis-gruet-deel** [comment]
Any Guidance/doc to tune the BSP for the 2x 50-pin FFC and 10-pin FFC PCIe x1 ?
