### ISSUE TITLE
the max dissipation of the nx module

### ISSUE THREAD

**Issue by sunzhongmeng** [antmicro/jetson-nano-baseboard#11]
hello,in the latest version i found the supply is tps54561,the max current is 5A,assume the nx module work in 15W model and the USB device need 2A current ,it seems the supply can't provide enouth current.By the way ,dit the new version of the board has been verified?

**Comment by pkatarzynski** [comment]
The on-board DC/DC is indeed tailored for 25W. The total power consumption of the Jetson Xavier NX and peripheral interfaces (USB devices or CSI cameras) need to fit within this range. This board is mostly a technology demonstrator. It does not cover all of the possible usage scenarios.
We have tested the prototypes for release 1.4.2. You can check out  our latest blog release in that matter.
https://antmicro.com/blog/2020/04/updated-jetson-nano-xavier-nx-baseboard-m2/
We hope to describe some more integrations soon.
