### ISSUE TITLE
buck capacitors for the Jetson NX SOM

### ISSUE THREAD

**Issue by sunzhongmeng** [antmicro/jetson-nano-baseboard#14]
the Jetson NX Developer Kit has three capacitors(C145/C146/C147 330uF) for the SOM +5V power supply.But this design just placed two 100uF capacitors (C10/C11),by the way the MLCC has 'DC Bias' character,at +5V the capacitor will be reduce.I have my own carrier board has only two buck capacitors(two 100uF),when i run some programs to test the GPU load the board will be closed(because of the +5V supply droped below 4.75V).

**Comment by pkatarzynski** [comment]
We were testing the Jetson Nano Baseboard with NVIDIA Jetson Xavier NX installed and a bunch of benchmarks from https://github.com/NVIDIA-AI-IOT/jetson_benchmarks. This setup worked stable for us.
Please note that the main power supply for the board should be over 5V DC (we have 9V DC suggestion on schematics) to make the on-board DC/DC converter produce 5 VDC required for the SoM.
The board is compact-sized so we are limitted in PCB space available for the filtering capacitors. We are planning to squeeze more of them in the next revision.
