### ISSUE TITLE
Any update on Kicad files?

### ISSUE THREAD

**Issue by BlueWaterCrystal** [antmicro/jetson-nano-baseboard#15]
what stage are the Kicad files currently at?

#3 
> We have a KiCad version of this board converted from Altium files. We hope to share this version soon.

**Comment by tkircher** [comment]
I'd like to know too. I'm interested in a board with this form factor, but stripped down to the SoM connector, DC power, M.2 connector, USB 3.0, and debug port. Would be nice if I could route that in four layers and get it made at OSHpark. ;)

**Comment by vanbwodonk** [comment]
I'm waiting for this too.

**Comment by ghost** [comment]
Hi,

Definitely would be interrested in that too!

**Comment by robodevchampion** [comment]
Hello Everyone, I am working on the same project, and completed the schematic and PCB is going to be completed in 2 more days. Any one here who is experienced PCB designer and is interested in this project and who can review my PCB are welcome. I am ready to share project. It will be helpful for other also.

PS: I am not an experienced PCB designer for high speed designs.
Thanks

**Comment by tkircher** [comment]
One big advantage of the Jetson SoM is that most of the critical high speed design is done for you.

**Comment by ghost** [comment]
> Hello Everyone, I am working on the same project, and completed the schematic and PCB is going to be completed in 2 more days. Any one here who is experienced PCB designer and is interested in this project and who can review my PCB are welcome. I am ready to share project. It will be helpful for other also.
> 
> PS: I am not an experienced PCB designer for high speed designs.
> Thanks

Awesome thank you! Not a professional either but I'd be happy to have a look at it! :)

**Comment by pkatarzynski** [comment]
We are working on the KiCad version. The design files will be released soon.

**Comment by ghost** [comment]
> We are working on the KiCad version. The design files will be released soon.

Hi,

Any updates on that?

Thanks

**Comment by pkatarzynski** [comment]
Please take a look at the branch https://github.com/antmicro/jetson-nano-baseboard/tree/kicad-version
