### ISSUE TITLE
Problem with the HDMI

### ISSUE THREAD

**Issue by gabgiani** [antmicro/jetson-nano-baseboard#16]
HI. we are working with a modified version of your board adding other peripherals. 
We have a problem with the HDMI. The board recognise correctly the MONITOR. But I don't have video, any monitor say: NO SIGNAL. But when I connect the HDMI cable the VNC adjust the resolution automatically with the new monitor.

I review all the design and is the HDMI area is exactly your design. 

I installed the last l4t version 4.5 and didn't work. I used the previous and when boot appear not good defined the NVIDIA LOGO. Now I downgrade other version and I can see distorted the image with the initial SETUP of UBUNTU.
Some suggestions?

I'm attaching the dmesg: 

27.961495] extcon-disp-state extcon:disp-state: cable 47 state 1
[   27.961501] Extcon AUX1(HDMI) enable
[   27.961902] extcon-disp-state extcon:disp-state: cable 51 state 1
[   27.961905] Extcon HDMI: HPD enabled
[   27.961947] tegradc tegradc.0: hdmi: plugged
[   27.971100] tegradc tegradc.0: blank - powerdown
[   28.026888] extcon-disp-state extcon:disp-state: cable 47 state 0
[   28.026890] Extcon AUX1(HDMI) disable
[   28.047209] tegradc tegradc.0: unblank
[   28.058165] tegradc tegradc.0: nominal-pclk:148500000 parent:148500000 div:1.0 pclk:148500000 147015000~161865000
[   28.058250] tegradc tegradc.0: hdmi: tmds rate:148500K prod-setting:prod_c_hdmi_75m_150m
[   28.059266] tegradc tegradc.0: hdmi: get RGB quant from EDID.
[   28.059273] tegradc tegradc.0: hdmi: get YCC quant from EDID.
[   28.097834] extcon-disp-state extcon:disp-state: cable 47 state 1
[   28.097839] Extcon AUX1(HDMI) enable
[   28.098118] tegradc tegradc.0: unblank
[   28.098125] tegradc tegradc.1: blank - powerdown
[   28.139675] tegradc tegradc.0: unblank
[   28.139834] tegradc tegradc.1: blank - powerdown

Best Regards

Gabriel 

![Untitled](https://user-images.githubusercontent.com/1419593/105395617-d7884500-5c16-11eb-87f5-38bfaffd58e5.png)

**Comment by ahmetcanack** [comment]
Are you using the correct SOM, I believe there are 2 versions of modules, [You can see the differences here.](https://www.arducam.com/nvidia-jetson-nano-b01-update-dual-camera/)

I have also seen people designing custom carrier boards with the help of the documentation shared by Nvidia.  They were having problems with the ethernet. There is a lot of confusion about this.  Maybe this has to do something with your problem.

**Comment by Jslater85** [comment]
Hi, I have encountered similar problems as mentioned  by Gabriel.

Did you ever have any resolution to this issue with the HDMI?

Which SOM is the correct to use?

All the best!

Jake

**Comment by gabgiani** [comment]
We finally redesign the hdmi lanes to prevent the issue, following the rules of the hdmi design and we used the jetson carrier board to solve many small issues.
About the firmware for 4 cameras, finally we design it based in the e3333 dts in the jetpack and we have it published in our website.

Best regards

Gabriel Giani

**Comment by pkatarzynski** [comment]
Hi all, HDMI works properly on the original design and many derivatives we have been building. If you redesign the board yourself and you cannot get something to work on the derivative design, this is not something we can help with. If you need help to build your own board, feel free to reach out to us to use our commercial services.
