### ISSUE TITLE
how make the usb 3 in device mode?

### ISSUE THREAD

**Issue by cudnn** [antmicro/jetson-nano-baseboard#2]
how make the usb 3 in device mode?how pitch the linux kernel ?how reconfigure type c hardwire?

**Comment by mgielda** [comment]
I will close this one now - these are very generic questions which are not related to the baseboard itself but rather to Linux/NVIDIA Jetpack. For future reference, we do offer commercial support for customers who need help building software, if you require it please contact us at contact@antmicro.com
