### ISSUE TITLE
PCB files

### ISSUE THREAD

**Issue by kfriesth** [antmicro/jetson-nano-baseboard#3]
Would you export the pcb schematic and pcb layout files to kicad or gerber file formats?

**Comment by qume** [comment]
Perhaps a bit late, but there is a free online Altium viewer here:

[https://www.altium.com/viewer/](https://www.altium.com/viewer/)

Drag and drop the schdoc files, and it will show you the schematic, the BOM, and in the case of the PCB file, the layout

I'll be starting a KiCAD board for the nano soon, did you end up doing one? Any interest in sharing the project?

**Comment by pkatarzynski** [comment]
We have a KiCad version of this board converted from Altium files. We hope to share this version soon.

**Comment by qume** [comment]
@pkatarzynski great news, thanks very much. Looking forward to it

**Comment by AdrianCGonzalez** [comment]
Would it be possible to export the Altium PCB files to ASCII format?

**Comment by wgthompson** [comment]
Longshot but any chance we can get the files in eagle?

**Comment by wild929** [comment]
I am using Altium Circuit Studio and am unable to import the PCB layout. Is there a way that you can save the file as  a PCB 5.0 Binary file?

Cheers...

**Comment by pgielda** [comment]
Not sure if that helps but there is a branch with Kicad version: https://github.com/antmicro/jetson-nano-baseboard/tree/kicad-version

**Comment by wild929** [comment]
> Not sure if that helps but there is a branch with Kicad version: https://github.com/antmicro/jetson-nano-baseboard/tree/kicad-version

Thanks. I am downloading KiCad now in the hopes I can convert the file to PCB Binary 5. I really don't want to have to get up to speed on a new tool.

**Comment by wild929** [comment]
Perhaps a bit off topic but can you tell me if the TX2 NX 's USB3 (which is 3.0) and USB1 (2.0) port can be connected directly to a USB3.0 Type A port? Or does this connection require a controller / mux between SOM and port?

Thanks.

**Comment by pkatarzynski** [comment]
It is possible to connect the USB lanes you mentioned directly to an USB 3.0 type-A port.

**Comment by mgielda** [comment]
As the main branch has switched to KiCad now, this issue can now be closed.
