### ISSUE TITLE
Support for Orin NX?

### ISSUE THREAD

**Issue by amarburg** [antmicro/jetson-nano-baseboard#33]
Hi all.  Anyone looked into electrical forward compatibility with the Orin NX?

**Comment by pkatarzynski** [comment]
Hi. The Jeston Nano Baseboard should work with Jeston Orin NX  - we have already done some tests around it. 
We have also prepared the Jetson Orin Baseboard  (https://github.com/antmicro/jetson-orin-baseboard) which break-routes the Orin-specific interfaces.

**Comment by amarburg** [comment]
Ah, that's super, and I had not seen the Orin-specific baseboard.  Thank you!
