### ISSUE TITLE
Capacitors on the BOM 

### ISSUE THREAD

**Issue by S4WRXTTCS** [antmicro/jetson-nano-baseboard#4]
Some of the caps seem to be undersized for the expected voltages.  As an example C1, C2, C3, C4 are shown in the BOM as Murata Electronics P/N: GRM155R60G475ME

That's a 4V part, but C1 along with C2 are connected to HDMI_PWR which has 5V going to it. 

Other caps are under the expected voltages, but only barely so. There doesn't seem to be any capacitor de-rating used when creating the BOM.

**Comment by pkatarzynski** [comment]
Hi Jason

Thank you for your contribution. We are going to revise the BOM and update the capacitors for a bigger range of rated voltages.
