### ISSUE TITLE
HDMI pull down resistors

### ISSUE THREAD

**Issue by sunzhongmeng** [antmicro/jetson-nano-baseboard#7]
Hello ，the NVIDIA Jetson Nano Product Designe Guide  says "499Ω, 1% pull-downs must be disabled when Jetson Nano is off or in sleep mode to meet the HDMI VOFF requirement. The enable to the FET, enables the pull-downs when the HDMI interface is to be used"but this design delete all pull down resistors.does it work well?

**Comment by pkatarzynski** [comment]
We have simplified some of the interfaces to gain more space for routing and make the PCB smaller. The board is meant to work as technology demonstrator and evaluation platform which stays in always-on mode. Hence satisfying HDMI VOFF was not our priority. The PCBs in rev. 1.3 were displayed at our booth during Embedded World 2020 in [camera related application](https://www.linkedin.com/posts/antmicro-ltd_jetsonnano-xaviernx-opensource-activity-6638028555051638785-Hmo-/)

**Comment by sunzhongmeng** [comment]
> We have simplified some of the interfaces to gain more space for routing and make the PCB smaller. The board is meant to work as technology demonstrator and evaluation platform which stays in always-on mode. Hence satisfying HDMI VOFF was not our priority. The PCBs in rev. 1.3 were displayed at our booth during Embedded World 2020 in [camera related application](https://www.linkedin.com/posts/antmicro-ltd_jetsonnano-xaviernx-opensource-activity-6638028555051638785-Hmo-/)

I see ，thank u.
