### ISSUE TITLE
the width of the VIN to TPS54561

### ISSUE THREAD

**Issue by sunzhongmeng** [antmicro/jetson-nano-baseboard#8]
The copper of the top layer is 0.035mm,the width of VIN tracks to the TPS54561 is 0.4mm,the power need atlest 5V*4A=20W,so i think the current of VIN is 20W/12V=1.67A,The width seems not enough

**Comment by pkatarzynski** [comment]
Hi sunzhongmeng
Thank you for spotting this. We are currently working on rev 1.4 of the design.  The PCB layout has been modified and power distribution planes have been widened accordingly to the expected current density. I hope to update the design files after verification on prototypes.

**Comment by sunzhongmeng** [comment]
OK,I got it.because the NX's power dissipation will be 15W,perhaps the +5V supply will more the 5A .
