### ISSUE TITLE
Pin Error of TPD8S009 

### ISSUE THREAD

**Issue by sunzhongmeng** [antmicro/jetson-nano-baseboard#9]
The VCC pins of the TPD8S009 are Pin 13 and Pin15,not Pin14.

**Comment by pkatarzynski** [comment]
Hi sunzhonmeng

You are right, the TPD8S009 chip is still to power supply via pin13 and pin14 (which is effectively a NC pin) in the design so it worked properly on prototypes. Nevertheless the pin to pad assignment in this component needs to be fixed.
Thank you for spotting this.
